language: objective-c
osx_image: xcode9.3

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="Outlaw"
    - PROJECT_SUFFFIX=".xcodeproj"
    - FRAMEWORK_SCHEME="Outlaw"
    - IOS_SDK=iphonesimulator11.3
    - TVOS_SDK=appletvsimulator11.3
    - OSX_SDK=macosx10.13
  matrix:
    - DESTINATION="OS=11.3,name=iPhone 8 Plus"       SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="OS=11.3,name=Apple TV 4K"         SCHEME="$FRAMEWORK_SCHEME" SDK="$TVOS_SDK"
    - DESTINATION="arch=x86_64"                      SCHEME="$FRAMEWORK_SCHEME" SDK="$OSX_SDK"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project "$PROJECT_NAME$PROJECT_SUFFFIX" -scheme "$SCHEME" -sdk "$SDK" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash) -J "$PROJECT_NAME"

notifications:
  email: false
